version: '3.7'

services:
  findpet_database:
    image: postgres
    container_name: findpet_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=findpet
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=findpet
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: findpet
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  pgdata:
   driver: local